// This file is generated by the build process. Do not edit it directly. See 'master.pkl'.

// Name of the company or vendor which makes this software.
export const companyName = "2am Logic";

// Name of this software product.
export const productName = "Genstack";

// URL-friendly name of this software product.
export const productSlug = "genstack";
